gui:
  shortTimeFormat: '15:04:05'

customCommands:
  - key: "c"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
