#!/bin/bash

ID="$(ip link | awk '/state UP/ {print $2}')"

network_status() {
  if [[ $ID == e* ]]; then
    echo "Online"
  else
    iwgetid -r || echo "Offline"
  fi
}

network_visible() {
  echo "true"
}

if [[ "$1" == "--visible" ]]; then
  network_visible
elif [[ "$1" == "--status" ]]; then
  network_status
fi
